export { default as SplashScreen } from './SplashScreen'
export { default as Login } from './Login'
export { default as CreateAccount } from './CreateAccount'
export { default as ForgotPassword } from './ForgotPassword'
export { default as Home } from './Home'
export { default as CustomerProfile } from './Customer/Profile'
export { default as ProfessionalDetails } from './Customer/ProfessionalDetails'
export { default as ProfessionalsProfile } from './Professionals/Profile'
